name: Deploy to EKS with Kustomize

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to main

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      # Step 3: Setup kubectl
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # Step 4: Update kubeconfig for EKS
      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name advanced-kustomize-cluster --region eu-north-1

      # Step 5: Deploy using Kustomize (Production)
      - name: Deploy Kustomize Production Overlay
        run: |
          kubectl apply -k overlays/production
          kubectl rollout status deployment/kustomize-app

